### ISSUE TITLE
AD Password / Passcode / Agree to terms

### ISSUE THREAD

**Issue by sc0ttkclark** [ericmann/openconnect-vm#9]
Any ideas on how to best pass in the AD Password / Passcode to config?

Also, when using AnyConnect for this VPN host it comes back with a requirement to click Agree to their terms. Is this going to present any issues when connecting via Openconnect?

**Comment by sc0ttkclark** [comment]
For now I'm doing the following steps:
1. Start up the openconnect vagrant instance
2. Start up the openconnect vagrant instance
3. `vagrant ssh` to connect to SSH into vagrant
4. `sudo su` to switch to root
5. `screen` to start up a screen that keeps going even though I can close my terminal
6. `openconnect --user="{USER}" {VPN URL HERE} --no-xmlpost --script /etc/vpnc/vpnc-script`

This then asks for two separate passwords: my AD Password and my passcode (via RSA SecurID).

Works :)

**Comment by ericmann** [comment]
Not sure if there's a way to bypass that ... One possibility would be a Bash (or similar) script that does all of the ssh/su/screen work for you to give you an interactive terminal through wich you can provide passwords. I'm assuming the AD password is static, but I'm not even sure how to begin passing a dynamic passcode ...

**Comment by sc0ttkclark** [comment]
I have to admit, this was really only put here for the sake of my future self and others who may need a similar solution.

I'd assume you could get bash to ask for a 'Passcode' after it asks for a 'AD Password' in this config. Not volunteering to spend time on it since my solution works for me and thus I'm happy with it :)
